{{- if .Values.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nautobot-media
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nautobot.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.media.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.media.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nautobot-static
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nautobot.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.static.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.static.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nautobot-git
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nautobot.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.git.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.git.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
{{- end }}
