#!/bin/bash
# Manual Kubernetes Deployment Helper Script
# This script generates exact commands for your infrastructure

set -e

MASTER_IP="172.17.152.109"
WORKER_IPS=(
  "172.17.152.103"
  "172.17.152.104"
  "172.17.152.105"
  "172.17.152.106"
  "172.17.152.108"
)

echo "=========================================="
echo "KUBERNETES MANUAL DEPLOYMENT HELPER"
echo "=========================================="
echo ""

echo "📋 STEP 1: CLEAN ALL NODES"
echo "Run this command from your jumpbox:"
echo ""
echo "for ip in ${MASTER_IP} ${WORKER_IPS[@]}; do"
echo "  ssh ubuntu@\$ip \"sudo kubeadm reset -f && sudo rm -rf /etc/kubernetes /var/lib/kubelet /var/lib/etcd ~/.kube /root/.kube /etc/cni/net.d /opt/cni /var/lib/cni && sudo systemctl restart containerd kubelet\""
echo "done"
echo ""
read -p "Press Enter after you've cleaned all nodes..."

echo ""
echo "=========================================="
echo "📋 STEP 2: INITIALIZE MASTER NODE"
echo "=========================================="
echo ""
echo "SSH to master: ssh ubuntu@${MASTER_IP}"
echo ""
echo "Then run:"
echo "sudo kubeadm init \\"
echo "  --pod-network-cidr=10.244.0.0/16 \\"
echo "  --service-cidr=10.96.0.0/12 \\"
echo "  --apiserver-advertise-address=${MASTER_IP} \\"
echo "  --control-plane-endpoint=${MASTER_IP}:6443"
echo ""
echo "After initialization completes, setup kubeconfig:"
echo "mkdir -p \$HOME/.kube"
echo "sudo cp -i /etc/kubernetes/admin.conf \$HOME/.kube/config"
echo "sudo chown \$(id -u):\$(id -g) \$HOME/.kube/config"
echo ""
read -p "Press Enter after master is initialized and kubeconfig is setup..."

echo ""
echo "=========================================="
echo "📋 STEP 3: INSTALL FLANNEL CNI"
echo "=========================================="
echo ""
echo "On the master node (${MASTER_IP}), run:"
echo "kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml"
echo ""
echo "Wait for Flannel pods to become Running:"
echo "kubectl get pods -n kube-flannel -w"
echo "(Press Ctrl+C when all pods show Running)"
echo ""
echo "Verify master node becomes Ready:"
echo "kubectl get nodes"
echo ""
read -p "Press Enter after Flannel is installed and master is Ready..."

echo ""
echo "=========================================="
echo "📋 STEP 4: GET JOIN COMMAND"
echo "=========================================="
echo ""
echo "On master node, run:"
echo "sudo kubeadm token create --print-join-command"
echo ""
echo "COPY THE ENTIRE OUTPUT - you'll need it for the next step!"
echo ""
read -p "Press Enter when you have copied the join command..."

echo ""
echo "=========================================="
echo "📋 STEP 5: JOIN WORKER NODES"
echo "=========================================="
echo ""
echo "For EACH worker, SSH and run the join command you copied:"
echo ""

for i in "${!WORKER_IPS[@]}"; do
  echo "Worker $((i+1)): ssh ubuntu@${WORKER_IPS[$i]}"
  echo "  sudo kubeadm join ${MASTER_IP}:6443 --token <TOKEN> --discovery-token-ca-cert-hash sha256:<HASH>"
  echo ""
done

echo "Expected output for each: \"This node has joined the cluster\""
echo ""
echo "If join fails with 'already exists' error on any worker:"
echo "  sudo kubeadm reset -f"
echo "  sudo rm -rf /etc/kubernetes /var/lib/kubelet/pki"
echo "  sudo systemctl restart kubelet && sleep 5"
echo "  Then retry the join command"
echo ""
read -p "Press Enter after ALL workers have joined..."

echo ""
echo "=========================================="
echo "📋 STEP 6: VERIFY CLUSTER"
echo "=========================================="
echo ""
echo "On master node, run:"
echo "kubectl get nodes -o wide"
echo ""
echo "Expected: All 6 nodes in Ready state"
echo ""
echo "Check system pods:"
echo "kubectl get pods -n kube-system"
echo ""
echo "Check Flannel:"
echo "kubectl get pods -n kube-flannel"
echo ""
echo "All pods should be Running!"
echo ""
read -p "Press Enter when cluster shows all nodes Ready..."

echo ""
echo "=========================================="
echo "📋 STEP 7: DEPLOY NAUTOBOT"
echo "=========================================="
echo ""
echo "On master node, run these commands:"
echo ""
echo "# Create namespace"
echo "kubectl create namespace nautobot"
echo ""
echo "# Add Helm repo (if Helm not installed, install first)"
echo "helm repo add nautobot https://nautobot.github.io/helm-charts/"
echo "helm repo update"
echo ""
echo "# Deploy Nautobot"
echo "helm install nautobot nautobot/nautobot -n nautobot \\"
echo "  --set postgresql.enabled=true \\"
echo "  --set postgresql.auth.password=nautobot123 \\"
echo "  --set redis.enabled=true \\"
echo "  --set nautobot.superuser.enabled=true \\"
echo "  --set nautobot.superuser.username=admin \\"
echo "  --set nautobot.superuser.password=admin \\"
echo "  --set nautobot.superuser.email=admin@example.com"
echo ""
echo "# Wait for pods"
echo "kubectl get pods -n nautobot -w"
echo "(Press Ctrl+C when all pods Running)"
echo ""
echo "# Get service info"
echo "kubectl get svc -n nautobot"
echo ""
read -p "Press Enter when Nautobot is deployed..."

echo ""
echo "=========================================="
echo "✅ DEPLOYMENT COMPLETE!"
echo "=========================================="
echo ""
echo "Verify everything:"
echo "  kubectl get nodes                    # All 6 nodes Ready"
echo "  kubectl get pods -A | grep -v Running # Should show no output (all Running)"
echo "  kubectl get svc -n nautobot          # Get Nautobot access URL"
echo ""
echo "Access Nautobot:"
echo "  http://<any-node-ip>:<nodeport>"
echo "  Username: admin"
echo "  Password: admin"
echo ""
echo "=========================================="
echo "IMPORTANT: If API crashes during deployment:"
echo "  1. Wait 2-3 minutes for automatic recovery"
echo "  2. Run: ssh ubuntu@${MASTER_IP} 'sudo systemctl restart kubelet'"
echo "  3. Continue from where you left off"
echo "=========================================="
